baseurl = "https://example.com"
languageCode = "en"
defaultContentLanguage = "en"
title = "2019 JP Morgan"
theme = "hugo-theme-dream"

# copyright = ""

# googleAnalytics = ""

# disqusShortname = ""

# enableRobotsTXT = true

[params]
  author = "Antonio Tito"
  motto = "Providing Market Intelligence to Medical Metrics, Inc"
  # description = ""
  # avatar = ""
  
  # email = "atito@medicalmetrics.com"
  # github = ""
  # linkedin = ""
  # codepen = ""
  # stackoverflow = ""

  siteStartYear = 2018
  aboutHeader = "AboutMe"

  paginate = 4

  # favicon = "/favicon.ico"
